package com.security.baotai.mapper;

import com.security.baotai.model.VehicleRecord;
import com.security.baotai.model.VehicleRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VehicleRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vehicle_record
     *
     * @mbggenerated
     */
    int countByExample(VehicleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vehicle_record
     *
     * @mbggenerated
     */
    int deleteByExample(VehicleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vehicle_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vehicle_record
     *
     * @mbggenerated
     */
    int insert(VehicleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vehicle_record
     *
     * @mbggenerated
     */
    int insertSelective(VehicleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vehicle_record
     *
     * @mbggenerated
     */
    List<VehicleRecord> selectByExample(VehicleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vehicle_record
     *
     * @mbggenerated
     */
    VehicleRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vehicle_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") VehicleRecord record, @Param("example") VehicleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vehicle_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") VehicleRecord record, @Param("example") VehicleRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vehicle_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VehicleRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_vehicle_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VehicleRecord record);
}