package com.security.baotai.model.personnel;

import java.io.Serializable;
import java.util.Date;

public class Staff implements Serializable {
    private Long id;

    private String name;

    private String phone;

    private Boolean isSoldier;

    private String idNum;

    private String idPhotoAbove;

    private String idPhotoBack;

    private String politicalExamination;

    private String photo;

    private Date birthday;

    private Date entryDate;

    private Date leaveDate;

    private String department;

    private String role;

    private String remark;

    private Integer status;

    private Date createTime;

    private String createUserId;

    private Date updateTime;

    private String updateUserId;

    private String resume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_staff
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.id
     *
     * @return the value of tb_staff.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.id
     *
     * @param id the value for tb_staff.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.name
     *
     * @return the value of tb_staff.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.name
     *
     * @param name the value for tb_staff.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.phone
     *
     * @return the value of tb_staff.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.phone
     *
     * @param phone the value for tb_staff.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.is_soldier
     *
     * @return the value of tb_staff.is_soldier
     *
     * @mbggenerated
     */
    public Boolean getIsSoldier() {
        return isSoldier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.is_soldier
     *
     * @param isSoldier the value for tb_staff.is_soldier
     *
     * @mbggenerated
     */
    public void setIsSoldier(Boolean isSoldier) {
        this.isSoldier = isSoldier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.id_num
     *
     * @return the value of tb_staff.id_num
     *
     * @mbggenerated
     */
    public String getIdNum() {
        return idNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.id_num
     *
     * @param idNum the value for tb_staff.id_num
     *
     * @mbggenerated
     */
    public void setIdNum(String idNum) {
        this.idNum = idNum == null ? null : idNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.id_photo_above
     *
     * @return the value of tb_staff.id_photo_above
     *
     * @mbggenerated
     */
    public String getIdPhotoAbove() {
        return idPhotoAbove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.id_photo_above
     *
     * @param idPhotoAbove the value for tb_staff.id_photo_above
     *
     * @mbggenerated
     */
    public void setIdPhotoAbove(String idPhotoAbove) {
        this.idPhotoAbove = idPhotoAbove == null ? null : idPhotoAbove.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.id_photo_back
     *
     * @return the value of tb_staff.id_photo_back
     *
     * @mbggenerated
     */
    public String getIdPhotoBack() {
        return idPhotoBack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.id_photo_back
     *
     * @param idPhotoBack the value for tb_staff.id_photo_back
     *
     * @mbggenerated
     */
    public void setIdPhotoBack(String idPhotoBack) {
        this.idPhotoBack = idPhotoBack == null ? null : idPhotoBack.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.political_examination
     *
     * @return the value of tb_staff.political_examination
     *
     * @mbggenerated
     */
    public String getPoliticalExamination() {
        return politicalExamination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.political_examination
     *
     * @param politicalExamination the value for tb_staff.political_examination
     *
     * @mbggenerated
     */
    public void setPoliticalExamination(String politicalExamination) {
        this.politicalExamination = politicalExamination == null ? null : politicalExamination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.photo
     *
     * @return the value of tb_staff.photo
     *
     * @mbggenerated
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.photo
     *
     * @param photo the value for tb_staff.photo
     *
     * @mbggenerated
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.birthday
     *
     * @return the value of tb_staff.birthday
     *
     * @mbggenerated
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.birthday
     *
     * @param birthday the value for tb_staff.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.entry_date
     *
     * @return the value of tb_staff.entry_date
     *
     * @mbggenerated
     */
    public Date getEntryDate() {
        return entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.entry_date
     *
     * @param entryDate the value for tb_staff.entry_date
     *
     * @mbggenerated
     */
    public void setEntryDate(Date entryDate) {
        this.entryDate = entryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.leave_date
     *
     * @return the value of tb_staff.leave_date
     *
     * @mbggenerated
     */
    public Date getLeaveDate() {
        return leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.leave_date
     *
     * @param leaveDate the value for tb_staff.leave_date
     *
     * @mbggenerated
     */
    public void setLeaveDate(Date leaveDate) {
        this.leaveDate = leaveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.department
     *
     * @return the value of tb_staff.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.department
     *
     * @param department the value for tb_staff.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.role
     *
     * @return the value of tb_staff.role
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.role
     *
     * @param role the value for tb_staff.role
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.remark
     *
     * @return the value of tb_staff.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.remark
     *
     * @param remark the value for tb_staff.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.status
     *
     * @return the value of tb_staff.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.status
     *
     * @param status the value for tb_staff.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.create_time
     *
     * @return the value of tb_staff.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.create_time
     *
     * @param createTime the value for tb_staff.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.create_user_id
     *
     * @return the value of tb_staff.create_user_id
     *
     * @mbggenerated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.create_user_id
     *
     * @param createUserId the value for tb_staff.create_user_id
     *
     * @mbggenerated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.update_time
     *
     * @return the value of tb_staff.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.update_time
     *
     * @param updateTime the value for tb_staff.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.update_user_id
     *
     * @return the value of tb_staff.update_user_id
     *
     * @mbggenerated
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.update_user_id
     *
     * @param updateUserId the value for tb_staff.update_user_id
     *
     * @mbggenerated
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_staff.resume
     *
     * @return the value of tb_staff.resume
     *
     * @mbggenerated
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_staff.resume
     *
     * @param resume the value for tb_staff.resume
     *
     * @mbggenerated
     */
    public void setResume(String resume) {
        this.resume = resume == null ? null : resume.trim();
    }
}