package com.security.baotai.model.vehicle;

import java.io.Serializable;
import java.util.Date;

public class VehicleInformation implements Serializable {
    private Long id;

    private String licenseNum;

    private String department;

    private String driver;

    private Double mileage;

    private Date createTime;

    private String createUser;

    private Date updateTime;

    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_vehicle_information
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vehicle_information.id
     *
     * @return the value of tb_vehicle_information.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vehicle_information.id
     *
     * @param id the value for tb_vehicle_information.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vehicle_information.license_num
     *
     * @return the value of tb_vehicle_information.license_num
     *
     * @mbggenerated
     */
    public String getLicenseNum() {
        return licenseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vehicle_information.license_num
     *
     * @param licenseNum the value for tb_vehicle_information.license_num
     *
     * @mbggenerated
     */
    public void setLicenseNum(String licenseNum) {
        this.licenseNum = licenseNum == null ? null : licenseNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vehicle_information.department
     *
     * @return the value of tb_vehicle_information.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vehicle_information.department
     *
     * @param department the value for tb_vehicle_information.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vehicle_information.driver
     *
     * @return the value of tb_vehicle_information.driver
     *
     * @mbggenerated
     */
    public String getDriver() {
        return driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vehicle_information.driver
     *
     * @param driver the value for tb_vehicle_information.driver
     *
     * @mbggenerated
     */
    public void setDriver(String driver) {
        this.driver = driver == null ? null : driver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vehicle_information.mileage
     *
     * @return the value of tb_vehicle_information.mileage
     *
     * @mbggenerated
     */
    public Double getMileage() {
        return mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vehicle_information.mileage
     *
     * @param mileage the value for tb_vehicle_information.mileage
     *
     * @mbggenerated
     */
    public void setMileage(Double mileage) {
        this.mileage = mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vehicle_information.create_time
     *
     * @return the value of tb_vehicle_information.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vehicle_information.create_time
     *
     * @param createTime the value for tb_vehicle_information.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vehicle_information.create_user
     *
     * @return the value of tb_vehicle_information.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vehicle_information.create_user
     *
     * @param createUser the value for tb_vehicle_information.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vehicle_information.update_time
     *
     * @return the value of tb_vehicle_information.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vehicle_information.update_time
     *
     * @param updateTime the value for tb_vehicle_information.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_vehicle_information.update_user
     *
     * @return the value of tb_vehicle_information.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_vehicle_information.update_user
     *
     * @param updateUser the value for tb_vehicle_information.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}